// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // AlmacenProductos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class AlmacenProducto
    {
        public int ProductoId { get; set; } // ProductoId (Primary key)
        public int AlmacenId { get; set; } // AlmacenId (Primary key)
        public string UsuarioCreadorId { get; set; } // UsuarioCreadorId (Primary key) (length: 128)
        public decimal Stock { get; set; } // Stock (Primary key)
        public decimal CostoPromedio { get; set; } // CostoPromedio (Primary key)
        public System.DateTime FechaUltimo { get; set; } // FechaUltimo (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Almacene pointed by [AlmacenProductos].([AlmacenId]) (FK_AlmacenProductos_Almacenes)
        /// </summary>
        public virtual Almacene Almacene { get; set; } // FK_AlmacenProductos_Almacenes

        /// <summary>
        /// Parent Producto pointed by [AlmacenProductos].([ProductoId]) (FK_AlmacenProductos_Productos)
        /// </summary>
        public virtual Producto Producto { get; set; } // FK_AlmacenProductos_Productos

        public AlmacenProducto()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
