// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Almacenes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AlmaceneConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Almacene>
    {
        public AlmaceneConfiguration()
            : this("dbo")
        {
        }

        public AlmaceneConfiguration(string schema)
        {
            ToTable("Almacenes", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SucursalId).HasColumnName(@"SucursalId").HasColumnType("int").IsRequired();
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired();
            Property(x => x.UsuarioCreadorId).HasColumnName(@"UsuarioCreadorId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.UsuarioModificadorId).HasColumnName(@"UsuarioModificadorId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.Codigo).HasColumnName(@"Codigo").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Descripcion).HasColumnName(@"Descripcion").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(300);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.ValorMin).HasColumnName(@"ValorMin").HasColumnType("decimal").IsRequired().HasPrecision(18,6);
            Property(x => x.ValorMax).HasColumnName(@"ValorMax").HasColumnType("decimal").IsRequired().HasPrecision(18,6);
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.Empresa).WithMany(b => b.Almacenes).HasForeignKey(c => c.SucursalId).WillCascadeOnDelete(false); // FK_Almacenes_Empresas
            HasRequired(a => a.Sucursale).WithMany(b => b.Almacenes).HasForeignKey(c => c.SucursalId).WillCascadeOnDelete(false); // FK_Almacenes_Sucursales
        }
    }

}
// </auto-generated>
