// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // AlmacenProductos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class AlmacenProductoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AlmacenProducto>
    {
        public AlmacenProductoConfiguration()
            : this("dbo")
        {
        }

        public AlmacenProductoConfiguration(string schema)
        {
            ToTable("AlmacenProductos", schema);
            HasKey(x => new { x.ProductoId, x.AlmacenId, x.Stock });

            Property(x => x.ProductoId).HasColumnName(@"ProductoId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AlmacenId).HasColumnName(@"AlmacenId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Stock).HasColumnName(@"Stock").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.FechaUltimo).HasColumnName(@"FechaUltimo").HasColumnType("datetime").IsOptional();

            // Foreign keys
            HasRequired(a => a.Almacene).WithMany(b => b.AlmacenProductoes).HasForeignKey(c => c.AlmacenId).WillCascadeOnDelete(false); // FK_AlmacenProductos_Almacenes
            HasRequired(a => a.Producto).WithMany(b => b.AlmacenProductoes).HasForeignKey(c => c.ProductoId).WillCascadeOnDelete(false); // FK_AlmacenProductos_Productos
        }
    }

}
// </auto-generated>
