// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Almacenes
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Almacene
    {
        public int Id { get; set; } // Id (Primary key)
        public int SucursalId { get; set; } // SucursalId
        public int EmpresaId { get; set; } // EmpresaId
        public string UsuarioCreadorId { get; set; } // UsuarioCreadorId (length: 128)
        public string UsuarioModificadorId { get; set; } // UsuarioModificadorId (length: 128)

        ///<summary>
        /// @Encabezado:Si@Label:Codigo@Capturable:Si
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// @Encabezado:Si@Label:Descripcion:@Capturable:Si
        ///</summary>
        public string Descripcion { get; set; } // Descripcion (length: 300)
        public bool Activo { get; set; } // Activo

        ///<summary>
        /// @Encabezado:Si@Label:Valor Minimo@Capturable:No
        ///</summary>
        public decimal ValorMin { get; set; } // ValorMin

        ///<summary>
        /// @Encabezado:Si@Label:Valor Maximo@Capturable:No
        ///</summary>
        public decimal ValorMax { get; set; } // ValorMax

        ///<summary>
        /// @Encabezado:Si@Label:Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha

        // Reverse navigation

        /// <summary>
        /// Child AlmacenProductoes where [AlmacenProductos].[AlmacenId] point to this entity (FK_AlmacenProductos_Almacenes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AlmacenProducto> AlmacenProductoes { get; set; } // AlmacenProductos.FK_AlmacenProductos_Almacenes
        /// <summary>
        /// Child InventarioFisicoes where [InventarioFisicos].[AlmacenId] point to this entity (FK_InventarioFisicos_Almacenes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<InventarioFisico> InventarioFisicoes { get; set; } // InventarioFisicos.FK_InventarioFisicos_Almacenes
        /// <summary>
        /// Child MaximosMinimoes where [MaximosMinimos].[AlmacenId] point to this entity (FK_MaximosMinimos_Almacenes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MaximosMinimo> MaximosMinimoes { get; set; } // MaximosMinimos.FK_MaximosMinimos_Almacenes
        /// <summary>
        /// Child Movimientoes where [Movimientos].[AlmacenId] point to this entity (FK_Movimientos_Almacenes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Movimiento> Movimientoes { get; set; } // Movimientos.FK_Movimientos_Almacenes

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Almacenes].([SucursalId]) (FK_Almacenes_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Almacenes_Empresas

        /// <summary>
        /// Parent Sucursale pointed by [Almacenes].([SucursalId]) (FK_Almacenes_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_Almacenes_Sucursales

        public Almacene()
        {
            AlmacenProductoes = new System.Collections.Generic.List<AlmacenProducto>();
            InventarioFisicoes = new System.Collections.Generic.List<InventarioFisico>();
            MaximosMinimoes = new System.Collections.Generic.List<MaximosMinimo>();
            Movimientoes = new System.Collections.Generic.List<Movimiento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
