// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Clientes
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Cliente
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmpresaId { get; set; } // EmpresaId
        public int UsuarioCreadorId { get; set; } // UsuarioCreadorId
        public int UsuarioModificadorId { get; set; } // UsuarioModificadorId

        ///<summary>
        /// Descripcion
        ///</summary>
        public string Descripcion { get; set; } // Descripcion (length: 300)

        ///<summary>
        /// Calle
        ///</summary>
        public string Calle { get; set; } // Calle (length: 300)
        public string Colonia { get; set; } // Colonia (length: 50)
        public string Ciudad { get; set; } // Ciudad (length: 50)

        ///<summary>
        /// Codigo Postal
        ///</summary>
        public string CodigoPostal { get; set; } // CodigoPostal (length: 50)
        public string Municipio { get; set; } // Municipio (length: 100)
        public string Estado { get; set; } // Estado (length: 100)
        public string Pais { get; set; } // Pais (length: 100)
        public string Telefono { get; set; } // Telefono (length: 50)
        public string Celular { get; set; } // Celular (length: 50)
        public string NombreContacto { get; set; } // NombreContacto (length: 500)

        ///<summary>
        /// RFC
        ///</summary>
        public string Rfc { get; set; } // Rfc (length: 100)
        public string Correo { get; set; } // Correo (length: 200)

        ///<summary>
        /// Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha
        public bool Activo { get; set; } // Activo
        public bool TieneCredito { get; set; } // TieneCredito
        public int DiasCredito { get; set; } // DiasCredito
        public decimal LimiteCredito { get; set; } // LimiteCredito

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Clientes].([EmpresaId]) (FK_Clientes_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Clientes_Empresas

        public Cliente()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
