// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Entradas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Entrada
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmpresaId { get; set; } // EmpresaId
        public int? ProveedorId { get; set; } // ProveedorId
        public string UsuarioCreadorId { get; set; } // UsuarioCreadorId (length: 128)
        public string UsuarioModificadorId { get; set; } // UsuarioModificadorId (length: 128)
        public System.DateTime FechaMovimiento { get; set; } // FechaMovimiento

        ///<summary>
        /// Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha
        public bool Activo { get; set; } // Activo

        // Reverse navigation

        /// <summary>
        /// Child EntradaDetalles where [EntradaDetalles].[EntradaId] point to this entity (FK_EntradaDetalles_Entradas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<EntradaDetalle> EntradaDetalles { get; set; } // EntradaDetalles.FK_EntradaDetalles_Entradas

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Entradas].([EmpresaId]) (FK_Entradas_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Entradas_Empresas

        public Entrada()
        {
            EntradaDetalles = new System.Collections.Generic.List<EntradaDetalle>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
