// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // EntradaDetalles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class EntradaDetalleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EntradaDetalle>
    {
        public EntradaDetalleConfiguration()
            : this("dbo")
        {
        }

        public EntradaDetalleConfiguration(string schema)
        {
            ToTable("EntradaDetalles", schema);
            HasKey(x => new { x.EntradaId, x.ProductoId, x.Cantidad, x.Costo, x.Costo1, x.Iva });

            Property(x => x.EntradaId).HasColumnName(@"EntradaId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductoId).HasColumnName(@"ProductoId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Cantidad).HasColumnName(@"Cantidad").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Costo).HasColumnName(@"Costo").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Costo1).HasColumnName(@"Costo1").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Iva).HasColumnName(@"Iva").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Entrada).WithMany(b => b.EntradaDetalles).HasForeignKey(c => c.EntradaId).WillCascadeOnDelete(false); // FK_EntradaDetalles_Entradas
            HasRequired(a => a.Producto).WithMany(b => b.EntradaDetalles).HasForeignKey(c => c.ProductoId).WillCascadeOnDelete(false); // FK_EntradaDetalles_Productos
        }
    }

}
// </auto-generated>
