// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Entradas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class EntradaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Entrada>
    {
        public EntradaConfiguration()
            : this("dbo")
        {
        }

        public EntradaConfiguration(string schema)
        {
            ToTable("Entradas", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired();
            Property(x => x.ProveedorId).HasColumnName(@"ProveedorId").HasColumnType("int").IsOptional();
            Property(x => x.UsuarioCreadorId).HasColumnName(@"UsuarioCreadorId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.UsuarioModificadorId).HasColumnName(@"UsuarioModificadorId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128);
            Property(x => x.FechaMovimiento).HasColumnName(@"FechaMovimiento").HasColumnType("datetime").IsRequired();
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("datetime").IsRequired();
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.Empresa).WithMany(b => b.Entradas).HasForeignKey(c => c.EmpresaId).WillCascadeOnDelete(false); // FK_Entradas_Empresas
        }
    }

}
// </auto-generated>
