// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // InventarioFisicos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class InventarioFisico
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmpresaId { get; set; } // EmpresaId
        public int SucursalId { get; set; } // SucursalId
        public int AlmacenId { get; set; } // AlmacenId
        public int ProductoId { get; set; } // ProductoId
        public string Serie { get; set; } // Serie (length: 50)
        public int Folio { get; set; } // Folio
        public int Indice { get; set; } // Indice
        public decimal Cantidad { get; set; } // Cantidad
        public bool Activo { get; set; } // Activo

        // Foreign keys

        /// <summary>
        /// Parent Almacene pointed by [InventarioFisicos].([AlmacenId]) (FK_InventarioFisicos_Almacenes)
        /// </summary>
        public virtual Almacene Almacene { get; set; } // FK_InventarioFisicos_Almacenes

        /// <summary>
        /// Parent Empresa pointed by [InventarioFisicos].([EmpresaId]) (FK_InventarioFisicos_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_InventarioFisicos_Empresas

        /// <summary>
        /// Parent Producto pointed by [InventarioFisicos].([ProductoId]) (FK_InventarioFisicos_Productos)
        /// </summary>
        public virtual Producto Producto { get; set; } // FK_InventarioFisicos_Productos

        /// <summary>
        /// Parent Sucursale pointed by [InventarioFisicos].([SucursalId]) (FK_InventarioFisicos_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_InventarioFisicos_Sucursales

        public InventarioFisico()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
