// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Lineas
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Linea
    {
        public int Id { get; set; } // Id (Primary key)
        public int? LineaId { get; set; } // LineaId
        public int EmpresaId { get; set; } // EmpresaId
        public int UsuarioCreadorId { get; set; } // UsuarioCreadorId
        public int UsuarioModificadorId { get; set; } // UsuarioModificadorId

        ///<summary>
        /// @Encabezado:Si@Label:Codigo@Capturable:Si
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// @Encabezado:Si@Label:Descripcion@Capturable:Si
        ///</summary>
        public string Descripcion { get; set; } // Descripcion (length: 300)
        public bool Activo { get; set; } // Activo

        ///<summary>
        /// @Encabezado:Si@Label:Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha

        // Reverse navigation

        /// <summary>
        /// Child Lineas where [Lineas].[LineaId] point to this entity (FK_Lineas_Lineas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Linea> Lineas { get; set; } // Lineas.FK_Lineas_Lineas
        /// <summary>
        /// Child Productoes where [Productos].[LineaId] point to this entity (FK_Productos_Lineas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Producto> Productoes { get; set; } // Productos.FK_Productos_Lineas

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Lineas].([EmpresaId]) (FK_Lineas_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Lineas_Empresas

        /// <summary>
        /// Parent Linea pointed by [Lineas].([LineaId]) (FK_Lineas_Lineas)
        /// </summary>
        public virtual Linea Linea_LineaId { get; set; } // FK_Lineas_Lineas

        public Linea()
        {
            Lineas = new System.Collections.Generic.List<Linea>();
            Productoes = new System.Collections.Generic.List<Producto>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
