// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // MaximosMinimos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MaximosMinimoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MaximosMinimo>
    {
        public MaximosMinimoConfiguration()
            : this("dbo")
        {
        }

        public MaximosMinimoConfiguration(string schema)
        {
            ToTable("MaximosMinimos", schema);
            HasKey(x => new { x.Id, x.AlmacenId, x.ProductoId, x.EmpresaId, x.ValorMin, x.ValorMax, x.Activo, x.Fecha });

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AlmacenId).HasColumnName(@"AlmacenId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProductoId).HasColumnName(@"ProductoId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ValorMin).HasColumnName(@"ValorMin").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ValorMax).HasColumnName(@"ValorMax").HasColumnType("decimal").IsRequired().HasPrecision(18,6).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("datetime").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Almacene).WithMany(b => b.MaximosMinimoes).HasForeignKey(c => c.AlmacenId).WillCascadeOnDelete(false); // FK_MaximosMinimos_Almacenes
            HasRequired(a => a.Empresa).WithMany(b => b.MaximosMinimoes).HasForeignKey(c => c.EmpresaId).WillCascadeOnDelete(false); // FK_MaximosMinimos_Empresas
            HasRequired(a => a.Producto).WithMany(b => b.MaximosMinimoes).HasForeignKey(c => c.ProductoId).WillCascadeOnDelete(false); // FK_MaximosMinimos_Productos
        }
    }

}
// </auto-generated>
