// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Monedas
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Moneda
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmpresaId { get; set; } // EmpresaId
        public string UsuarioCreadorId { get; set; } // UsuarioCreadorId (length: 128)
        public string UsuarioModificadorId { get; set; } // UsuarioModificadorId (length: 128)

        ///<summary>
        /// @Encabezado:Si@Label:Codigo@Capturable:Si
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// @Encabezado:Si@Label:Descripcion@Capturable:Si
        ///</summary>
        public byte[] Descripcion { get; set; } // Descripcion (length: 300)

        ///<summary>
        /// @Encabezado:Si@Label:Valor Actual@Capturable:Si
        ///</summary>
        public decimal ValorActual { get; set; } // ValorActual
        public bool Activo { get; set; } // Activo

        ///<summary>
        /// @Encabezado:Si@Label:Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha

        // Reverse navigation

        /// <summary>
        /// Child Productoes where [Productos].[MonedaId] point to this entity (FK_Productos_Monedas)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Producto> Productoes { get; set; } // Productos.FK_Productos_Monedas

        // Foreign keys

        /// <summary>
        /// Parent Empresa pointed by [Monedas].([EmpresaId]) (FK_Monedas_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Monedas_Empresas

        public Moneda()
        {
            Productoes = new System.Collections.Generic.List<Producto>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
