// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Movimientos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class MovimientoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Movimiento>
    {
        public MovimientoConfiguration()
            : this("dbo")
        {
        }

        public MovimientoConfiguration(string schema)
        {
            ToTable("Movimientos", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.TipoMovimientoId).HasColumnName(@"TipoMovimientoId").HasColumnType("int").IsRequired();
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired();
            Property(x => x.AlmacenId).HasColumnName(@"AlmacenId").HasColumnType("int").IsRequired();
            Property(x => x.SucursalId).HasColumnName(@"SucursalId").HasColumnType("int").IsRequired();
            Property(x => x.ProductoId).HasColumnName(@"ProductoId").HasColumnType("int").IsRequired();
            Property(x => x.UsuarioCreadorId).HasColumnName(@"UsuarioCreadorId").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.Cantidad).HasColumnName(@"Cantidad").HasColumnType("decimal").IsRequired().HasPrecision(18,6);
            Property(x => x.CostoPromedio).HasColumnName(@"CostoPromedio").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Almacene).WithMany(b => b.Movimientoes).HasForeignKey(c => c.AlmacenId).WillCascadeOnDelete(false); // FK_Movimientos_Almacenes
            HasRequired(a => a.Empresa).WithMany(b => b.Movimientoes).HasForeignKey(c => c.EmpresaId).WillCascadeOnDelete(false); // FK_Movimientos_Empresas
            HasRequired(a => a.Producto).WithMany(b => b.Movimientoes).HasForeignKey(c => c.ProductoId).WillCascadeOnDelete(false); // FK_Movimientos_Productos
            HasRequired(a => a.Sucursale).WithMany(b => b.Movimientoes).HasForeignKey(c => c.SucursalId).WillCascadeOnDelete(false); // FK_Movimientos_Sucursales
            HasRequired(a => a.TiposMovimiento).WithMany(b => b.Movimientoes).HasForeignKey(c => c.TipoMovimientoId).WillCascadeOnDelete(false); // FK_Movimientos_TiposMovimiento
        }
    }

}
// </auto-generated>
