// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Movimientos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Movimiento
    {
        public int Id { get; set; } // Id (Primary key)
        public int TipoMovimientoId { get; set; } // TipoMovimientoId
        public int EmpresaId { get; set; } // EmpresaId
        public int AlmacenId { get; set; } // AlmacenId
        public int SucursalId { get; set; } // SucursalId
        public int ProductoId { get; set; } // ProductoId
        public string UsuarioCreadorId { get; set; } // UsuarioCreadorId (length: 128)
        public decimal Cantidad { get; set; } // Cantidad
        public decimal CostoPromedio { get; set; } // CostoPromedio
        public bool Activo { get; set; } // Activo
        public int Fecha { get; set; } // Fecha

        // Foreign keys

        /// <summary>
        /// Parent Almacene pointed by [Movimientos].([AlmacenId]) (FK_Movimientos_Almacenes)
        /// </summary>
        public virtual Almacene Almacene { get; set; } // FK_Movimientos_Almacenes

        /// <summary>
        /// Parent Empresa pointed by [Movimientos].([EmpresaId]) (FK_Movimientos_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Movimientos_Empresas

        /// <summary>
        /// Parent Producto pointed by [Movimientos].([ProductoId]) (FK_Movimientos_Productos)
        /// </summary>
        public virtual Producto Producto { get; set; } // FK_Movimientos_Productos

        /// <summary>
        /// Parent Sucursale pointed by [Movimientos].([SucursalId]) (FK_Movimientos_Sucursales)
        /// </summary>
        public virtual Sucursale Sucursale { get; set; } // FK_Movimientos_Sucursales

        /// <summary>
        /// Parent TiposMovimiento pointed by [Movimientos].([TipoMovimientoId]) (FK_Movimientos_TiposMovimiento)
        /// </summary>
        public virtual TiposMovimiento TiposMovimiento { get; set; } // FK_Movimientos_TiposMovimiento

        public Movimiento()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
