// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Planes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Plane
    {
        public int Id { get; set; } // Id (Primary key)
        public string Codigo { get; set; } // Codigo (length: 10)
        public string Descripcion { get; set; } // Descripcion (length: 100)
        public bool Activo { get; set; } // Activo
        public System.DateTime Fecha { get; set; } // Fecha

        // Reverse navigation

        /// <summary>
        /// Child Empresas where [Empresas].[TipoPlanId] point to this entity (FK_Empresas_Planes)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Empresa> Empresas { get; set; } // Empresas.FK_Empresas_Planes

        public Plane()
        {
            Empresas = new System.Collections.Generic.List<Empresa>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
