// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Productos
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class ProductoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Producto>
    {
        public ProductoConfiguration()
            : this("dbo")
        {
        }

        public ProductoConfiguration(string schema)
        {
            ToTable("Productos", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired();
            Property(x => x.CategoriaId).HasColumnName(@"CategoriaId").HasColumnType("int").IsOptional();
            Property(x => x.LineaId).HasColumnName(@"LineaId").HasColumnType("int").IsOptional();
            Property(x => x.ProveedorId).HasColumnName(@"ProveedorId").HasColumnType("int").IsOptional();
            Property(x => x.MonedaId).HasColumnName(@"MonedaId").HasColumnType("int").IsOptional();
            Property(x => x.Codigo).HasColumnName(@"Codigo").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Descripcion).HasColumnName(@"Descripcion").HasColumnType("varbinary").IsRequired().HasMaxLength(300);
            Property(x => x.Precio).HasColumnName(@"Precio").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Precio1).HasColumnName(@"Precio1").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Precio2).HasColumnName(@"Precio2").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Precio3).HasColumnName(@"Precio3").HasColumnType("money").IsRequired().HasPrecision(19,4);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("datetime").IsRequired();
            Property(x => x.Localizacion).HasColumnName(@"Localizacion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Observacion).HasColumnName(@"Observacion").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Imagen).HasColumnName(@"Imagen").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);

            // Foreign keys
            HasOptional(a => a.Categoria).WithMany(b => b.Productoes).HasForeignKey(c => c.CategoriaId).WillCascadeOnDelete(false); // FK_Productos_Categorias
            HasOptional(a => a.Linea).WithMany(b => b.Productoes).HasForeignKey(c => c.LineaId).WillCascadeOnDelete(false); // FK_Productos_Lineas
            HasOptional(a => a.Moneda).WithMany(b => b.Productoes).HasForeignKey(c => c.MonedaId).WillCascadeOnDelete(false); // FK_Productos_Monedas
            HasRequired(a => a.Empresa).WithMany(b => b.Productoes).HasForeignKey(c => c.EmpresaId).WillCascadeOnDelete(false); // FK_Productos_Empresas
        }
    }

}
// </auto-generated>
