// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // Productos
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class Producto
    {
        public int Id { get; set; } // Id (Primary key)
        public int EmpresaId { get; set; } // EmpresaId
        public int? CategoriaId { get; set; } // CategoriaId
        public int? LineaId { get; set; } // LineaId
        public int? ProveedorId { get; set; } // ProveedorId

        ///<summary>
        /// Codigo
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// Descripcion
        ///</summary>
        public byte[] Descripcion { get; set; } // Descripcion (length: 300)

        ///<summary>
        /// Precio
        ///</summary>
        public decimal Precio { get; set; } // Precio
        public decimal? Precio1 { get; set; } // Precio1
        public decimal? Precio2 { get; set; } // Precio2
        public decimal? Precio3 { get; set; } // Precio3
        public bool Activo { get; set; } // Activo

        ///<summary>
        /// Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha
        public string Localizacion { get; set; } // Localizacion (length: 200)
        public string Observacion { get; set; } // Observacion (length: 500)
        public string Imagen { get; set; } // Imagen (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child AlmacenProductoes where [AlmacenProductos].[ProductoId] point to this entity (FK_AlmacenProductos_Productos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<AlmacenProducto> AlmacenProductoes { get; set; } // AlmacenProductos.FK_AlmacenProductos_Productos
        /// <summary>
        /// Child EntradaDetalles where [EntradaDetalles].[ProductoId] point to this entity (FK_EntradaDetalles_Productos)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<EntradaDetalle> EntradaDetalles { get; set; } // EntradaDetalles.FK_EntradaDetalles_Productos

        // Foreign keys

        /// <summary>
        /// Parent Categoria pointed by [Productos].([CategoriaId]) (FK_Productos_Categorias)
        /// </summary>
        public virtual Categoria Categoria { get; set; } // FK_Productos_Categorias

        /// <summary>
        /// Parent Empresa pointed by [Productos].([EmpresaId]) (FK_Productos_Empresas)
        /// </summary>
        public virtual Empresa Empresa { get; set; } // FK_Productos_Empresas

        /// <summary>
        /// Parent Linea pointed by [Productos].([LineaId]) (FK_Productos_Lineas)
        /// </summary>
        public virtual Linea Linea { get; set; } // FK_Productos_Lineas

        public Producto()
        {
            AlmacenProductoes = new System.Collections.Generic.List<AlmacenProducto>();
            EntradaDetalles = new System.Collections.Generic.List<EntradaDetalle>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
