// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // TiposMovimiento
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class TiposMovimiento
    {
        public int Id { get; set; } // Id (Primary key)
        public int UsuarioId { get; set; } // UsuarioId
        public int UsuarioCreadorId { get; set; } // UsuarioCreadorId
        public int UsuarioModificadorId { get; set; } // UsuarioModificadorId

        ///<summary>
        /// @Encabezado:No@Label:Tipo@Capturable:Si
        ///</summary>
        public string Tipo { get; set; } // Tipo (length: 10)

        ///<summary>
        /// @Encabezado:Si@Label:Codigo@Capturable:Si
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// @Encabezado:Si@Label:Descripcion@Capturable:Si
        ///</summary>
        public string Descripcion { get; set; } // Descripcion (length: 300)

        ///<summary>
        /// @Encabezado:Si@Label:Clasificacion@Capturable:Si
        ///</summary>
        public string Clasificacion { get; set; } // Clasificacion (length: 50)
        public bool Activo { get; set; } // Activo

        ///<summary>
        /// @Encabezado:Si@Label:Fecha
        ///</summary>
        public System.DateTime Fecha { get; set; } // Fecha

        // Reverse navigation

        /// <summary>
        /// Child Movimientoes where [Movimientos].[TipoMovimientoId] point to this entity (FK_Movimientos_TiposMovimiento)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Movimiento> Movimientoes { get; set; } // Movimientos.FK_Movimientos_TiposMovimiento

        public TiposMovimiento()
        {
            Movimientoes = new System.Collections.Generic.List<Movimiento>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
