// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // TiposMovimiento
    ///<summary>
    /// Catalogo
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class TiposMovimiento
    {
        public int Id { get; set; } // Id (Primary key)
        public int UsuarioId { get; set; } // UsuarioId
        public int UsuarioCreadorId { get; set; } // UsuarioCreadorId
        public int UsuarioModificadorId { get; set; } // UsuarioModificadorId
        public string Tipo { get; set; } // Tipo (length: 10)

        ///<summary>
        /// Codigo
        ///</summary>
        public string Codigo { get; set; } // Codigo (length: 50)

        ///<summary>
        /// Descripcion
        ///</summary>
        public string Descripcion { get; set; } // Descripcion (length: 300)

        ///<summary>
        /// Clasificacion
        ///</summary>
        public string Clasificacion { get; set; } // Clasificacion (length: 50)
        public bool Activo { get; set; } // Activo
        public System.DateTime Fecha { get; set; } // Fecha

        public TiposMovimiento()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
