// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // TransferenciasInternas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public partial class TransferenciasInterna
    {
        public int Id { get; set; } // Id (Primary key)
        public int AlmacenOrigenId { get; set; } // AlmacenOrigenId
        public int AlmacenDestinoId { get; set; } // AlmacenDestinoId
        public int EmpresaId { get; set; } // EmpresaId
        public int ProductoId { get; set; } // ProductoId
        public int UsuarioCreadorId { get; set; } // UsuarioCreadorId
        public int UsuarioAproboId { get; set; } // UsuarioAproboId
        public string Serie { get; set; } // Serie (length: 50)
        public int Folio { get; set; } // Folio
        public string Concepto { get; set; } // Concepto (length: 50)
        public bool Activo { get; set; } // Activo
        public System.DateTime Fecha { get; set; } // Fecha
        public string Observacion { get; set; } // Observacion

        public TransferenciasInterna()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
