// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 1.4
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Farmacia.POS.Model
{
    using Farmacia.POS.Model;

    // TransferenciasInternas
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.1.0")]
    public class TransferenciasInternaConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TransferenciasInterna>
    {
        public TransferenciasInternaConfiguration()
            : this("dbo")
        {
        }

        public TransferenciasInternaConfiguration(string schema)
        {
            ToTable("TransferenciasInternas", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AlmacenOrigenId).HasColumnName(@"AlmacenOrigenId").HasColumnType("int").IsRequired();
            Property(x => x.AlmacenDestinoId).HasColumnName(@"AlmacenDestinoId").HasColumnType("int").IsRequired();
            Property(x => x.EmpresaId).HasColumnName(@"EmpresaId").HasColumnType("int").IsRequired();
            Property(x => x.ProductoId).HasColumnName(@"ProductoId").HasColumnType("int").IsRequired();
            Property(x => x.UsuarioCreadorId).HasColumnName(@"UsuarioCreadorId").HasColumnType("int").IsRequired();
            Property(x => x.UsuarioAproboId).HasColumnName(@"UsuarioAproboId").HasColumnType("int").IsRequired();
            Property(x => x.Serie).HasColumnName(@"Serie").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Folio).HasColumnName(@"Folio").HasColumnType("int").IsRequired();
            Property(x => x.Concepto).HasColumnName(@"Concepto").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Activo).HasColumnName(@"Activo").HasColumnType("bit").IsRequired();
            Property(x => x.Fecha).HasColumnName(@"Fecha").HasColumnType("datetime").IsRequired();
            Property(x => x.Observacion).HasColumnName(@"Observacion").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
        }
    }

}
// </auto-generated>
